# docker-compose:
# https://docs.docker.com/compose/overview/

version: '3.5'

services:
  orthanc:
    container_name: orthanc
    image: jodogne/orthanc-plugins
    volumes:
      - ../sampledata:/sampledata
    ports:
      - '4242:4242'
      - '8042:8042'
    restart: always
  viewer:
    container_name: ohif-viewer
    build:
      # Up to the root directory
      context: ../
      # Use our dockerfile to build the viewer
      dockerfile: dockerfile
    ports:
      - '80:80'
    depends_on:
      - orthanc
    environment:
      - NODE_ENV=production
      - REACT_APP_CONFIG=config/local_orthanc.js
    restart: always
    volumes:
      - ../config/local_orthanc.js:/usr/share/nginx/html/servers.js
  proxy:
    image: nginx
    restart: always
    ports:
      - 8899:80
    volumes:
      - ./nginx-proxy/conf/nginx.conf:/etc/nginx/nginx.conf:ro
