version: '3.5'

services:

  viewer:
    container_name: ohif-viewer
    build:
      context: ../
      dockerfile: Dockerfile
    ports:
      - '80:80'
    environment:
      - NODE_ENV=production
    volumes:
      - ../config/public_dicomweb.js:/usr/share/nginx/html/servers.js