version: '3.5'

services:
  viewer:
    container_name: ohif-viewer
    build:
      context: ../
      dockerfile: Dockerfile
    ports:
      - '80:80'
    environment:
      - NODE_ENV=production
      - REACT_APP_CONFIG=config/public_dicomweb
