version: '3.5'

services:
  keycloak_postgres:
    hostname: keycloak-db
    restart: always
    image: postgres
    volumes:
      - ./keycloak_postgres_data:/var/lib/postgresql
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    dns:
      - 8.8.8.8
  keycloak:
    hostname: keycloak
    restart: always
    image: jboss/keycloak:6.0.1
    environment:
      POSTGRES_PORT_5432_TCP_ADDR: keycloak_postgres
      POSTGRES_DATABASE: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: password
      PROXY_ADDRESS_FORWARDING: 'true'
    #    volumes:
    #      - ./keycloak_data/themes:/opt/jboss/keycloak/themes
    ports:
      - 8080:8080
    depends_on:
      - keycloak_postgres
    dns:
      - 8.8.8.8
    links:
      - keycloak_postgres
